# Generated by Django 3.2 on 2021-05-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_mobile_specs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='specs',
            field=models.CharField(max_length=120),
        ),
    ]
