# Generated by Django 3.2 on 2021-05-08 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_changepassword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Changepassword',
        ),
        migrations.DeleteModel(
            name='Mobile',
        ),
    ]
