# Generated by Django 3.2 on 2021-05-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_cart_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Ordered', 'Ordered'), ('Delivered', 'Delivered'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='Ordered', max_length=150),
        ),
    ]
